#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Workspace install:
  stage: "Prepare"
  dependencies: []
  image: node:12
  cache:
    key: "$CI_COMMIT_REF_SLUG-node_modules"
    paths:
      - $CI_PROJECT_DIR/.yarn
  artifacts:
    paths:
      - node_modules
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile --link-duplicates

Register socialgouv/domifa base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 1024M
    IMAGE_NAME: $CI_REGISTRY_IMAGE
