#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Workspace install:
  stage: "Prepare"
  dependencies: []
  image: node:12

  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_BUILD_REF_NAME-yarn-cache"
    paths:
      - .yarn.cache.tar
      - node_modules.tar
  before_script:
    - time tar -xpf .yarn.cache.tar || true
    - time tar -xpf node_modules.tar || true
  after_script:
    - time tar -cf .yarn.cache.tar .yarn
    - time tar -cf node_modules.tar node_modules packages/*/node_modules

  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile

Build backend:
  stage: "Build"

  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_BUILD_REF_NAME-yarn-cache"
    paths:
      - node_modules.tar
    policy: pull
  before_script:
    - time tar -xpf node_modules.tar

  script:
    - yarn workspace @domifa/backend build
