#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Workspace install:
  stage: "Prepare"
  dependencies: []
  image: node:12

  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_BUILD_REF_NAME-node_modules"
    paths:
      - .yarn.cache.tar
  before_script:
    - time tar -xpf .yarn.cache.tar $CI_PROJECT_DIR/.yarn || true
  after_script:
    - time tar -cf .yarn.cache.tar $CI_PROJECT_DIR/.yarn

  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile

