#

.prepare_stage: &prepare_stage
  extends: .base_register_stage
  stage: "Prepare"
  dependencies: []

#

Backend Install:
  stage: "Prepare"
  dependencies: []
  image: node:12

  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_BUILD_REF_NAME-node_modules"
    paths:
      - $CI_PROJECT_DIR/.yarn
  artifacts:
    paths:
      - node_modules

  script:
    - cd packages/backend
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile --focus

Frontend Install:
  stage: "Prepare"
  dependencies: []
  image: node:12

  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_BUILD_REF_NAME-node_modules"
    paths:
      - $CI_PROJECT_DIR/.yarn
  artifacts:
    paths:
      - node_modules

  script:
    - cd packages/frontend
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile --focus
